# Uncomment the next line to define a global platform for your project
# platform :ios, '17.5'

target 'Instagram-Firestore-Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instagram-Firestore-Clone
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Firestore'
	pod 'Firebase/Storage'
	pod 'Firebase/Messaging'
	pod 'Firebase/Auth'
	pod 'ActiveLabel'
	pod 'SDWebImage','~> 4.4.2'
	pod 'JGProgressHUD','~> 2.0.3'
 	pod 'YPImagePicker'
end

  # Post-installation script to adjust IPHONEOS_DEPLOYMENT_TARGET

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Sets IPHONEOS_DEPLOYMENT_TARGET to 17.5 in all libraries
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "17.5"
    end
  end
end